### ISSUE TITLE
The FlyingThings3D.zip may compress the wrong data

### ISSUE THREAD

**Issue by MaxChanger** [Lilac-Lee/Neural_Scene_Flow_Prior#1]
Thanks for releasing this amazing project.

As the title mentions, if I use the FlyingThings3D.zip downloaded from the Google Drive, nuscenes_sf.zip is obtained after decompression. 🤪
Hope to update and fix this link.
![image](https://user-images.githubusercontent.com/35401968/141070099-80750b14-4f74-4558-bdc2-00a10538ec2f.png)

**Comment by Lilac-Lee** [comment]
Oh, thanks for the reminder! I Will update soon.

**Comment by Lilac-Lee** [comment]
Just updated the link! Cheers.
