### ISSUE TITLE
Is this model a type of module?

### ISSUE THREAD

**Issue by russellgeum** [Lilac-Lee/Neural_Scene_Flow_Prior#2]
Is this your model just a module that attaches to models such as PWC-Net and FlowNet3D or Non rigid ICP etc ...
Is it a concept that can be attached to any backbone with point cloud input?

**Comment by Lilac-Lee** [comment]
Hi, this is an independent model that solves the scene flow problem on its own. The model is basically MLPs that directly optimize to get the flow. Cheers.
