### ISSUE TITLE
Ground Removal method

### ISSUE THREAD

**Issue by zwqnju** [Lilac-Lee/Neural_Scene_Flow_Prior#3]
Ground removal has been done in the dataset you provided. I wonder how to remove ground points exactly.

- FlyingThings3D: No ground points to be removed.
- KITTI: based on annotations by FlowNet3D's authors, right?
- Argoverse and nuScenes: "using the information provided by the ground height map" as your paper writes. But how do you get the ground height map?

**Comment by Lilac-Lee** [comment]
Hi. You're right about FlyingThings3D and KITTI. 
For Argoverse, you can refer to the [official Argoverse API](https://github.com/argoai/argoverse-api), and download the HD map data, then you'll find the height map provided by the map. You can also refer to the [competition tracking tutorial](https://github.com/argoai/argoverse-api/blob/master/demo_usage/competition_tracking_tutorial.ipynb) for more details.
For nuScenes, there is no height map provided by the official data, sorry for the confusion. We used RANSAC to remove the ground points.
