### ISSUE TITLE
Scene flow result visualiztion

### ISSUE THREAD

**Issue by zwqnju** [Lilac-Lee/Neural_Scene_Flow_Prior#4]
How to visualize scene flow result? Like the bottom pic in this figure: [link](https://github.com/Lilac-Lee/Neural_Scene_Flow_Prior/blob/main/imgs/scene_flow_argoverse.png) 

Can this part of code be provided?

**Comment by Lilac-Lee** [comment]
Hi, you can take a look at [custom_draw_geometry_with_key_callback function](https://github.com/Lilac-Lee/Neural_Scene_Flow_Prior/blob/5915f08fc4f4d10807dc7b5c8632e9dbd2778968/visualize.py#L262) in visualize.py. 

In the optimization.py, when you set "options.visualize==True", it will call the [visualization function](https://github.com/Lilac-Lee/Neural_Scene_Flow_Prior/blob/5915f08fc4f4d10807dc7b5c8632e9dbd2778968/optimization.py#L174). Then at the end of each optimization, you will see a similar plot to the figure, just follow the key callback instruction, and press "k" for dark background, use "+/-" to adjust the point size, use your mouse to change your viewpoint.

For the color wheel, you can take a look at [make_colorwheel funciton](https://github.com/Lilac-Lee/Neural_Scene_Flow_Prior/blob/5915f08fc4f4d10807dc7b5c8632e9dbd2778968/visualize.py#L64) in visualize.py.

Cheers.
